///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : pportcamera.h
/// SOFTWARE COMPONENT NAME           : PPortCamera
/// GENERATED DATE                    : 2024-11-22 14:30:35
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_CAMERA_AA_PPORTCAMERA_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_CAMERA_AA_PPORTCAMERA_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "deepracer/service/camera/svcamera_skeleton.h"
 
#include "ara/log/logger.h"
 
#include <mutex>
#include <thread>
 
namespace deepracer
{
namespace service
{
namespace camera
{
namespace skeleton
{
 
class SvCameraSkeletonImpl : public SvCameraSkeleton
{
public:
    /// @brief Constructor
    SvCameraSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent);

private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;

};
 
} /// namespace skeleton
} /// namespace camera
} /// namespace service
} /// namespace deepracer

namespace camera
{
namespace aa
{
namespace port
{
 
class PPortCamera
{
public:
    /// @brief Constructor
    PPortCamera();
    
    /// @brief Destructor
    ~PPortCamera();
    
    /// @brief Start port
    void Start();
    
    /// @brief Terminate port
    void Terminate();
    
    /// @brief Write event data to buffer, CamEvent
    void WriteDataCamEvent(const deepracer::service::camera::skeleton::events::CamEvent::SampleType& data);
     
    /// @brief Send event cyclic from buffer data, CamEvent
    void SendEventCamEventCyclic();
     
    /// @brief Send event directly from buffer data, CamEvent
    void SendEventCamEventTriggered();
     
    /// @brief Send event directly with argument, CamEvent
    void SendEventCamEventTriggered(const deepracer::service::camera::skeleton::events::CamEvent::SampleType& data);
     
private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    /// @brief Flag of port status
    bool m_running;
    
    /// @brief Mutex for this port
    std::mutex m_mutex;
    
    /// @brief AUTOSAR Port Interface
    std::unique_ptr<deepracer::service::camera::skeleton::SvCameraSkeletonImpl> m_interface;
    
    /// @brief Data for event, CamEvent
    deepracer::service::camera::skeleton::events::CamEvent::SampleType m_CamEventData;
};
 
} /// namespace port
} /// namespace aa
} /// namespace camera
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_CAMERA_AA_PPORTCAMERA_H