///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : pportinference.cpp
/// SOFTWARE COMPONENT NAME           : PPortInference
/// GENERATED DATE                    : 2024-11-22 14:30:35
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "inference/aa/port/pportinference.h"
 
namespace deepracer
{
namespace service
{
namespace inference
{
namespace skeleton
{
 
SvInfereceSkeletonImpl::SvInfereceSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode)
    : SvInfereceSkeleton(instanceSpec, mode)
    , m_logger(ara::log::CreateLogger("INFE", "PORT", ara::log::LogLevel::kVerbose))
{
}
 
} /// namespace skeleton
} /// namespace inference
} /// namespace service
} /// namespace deepracer

namespace inference
{
namespace aa
{
namespace port
{
 
PPortInference::PPortInference()
    : m_logger(ara::log::CreateLogger("INFE", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_InfEventData{0U}
{
}
 
PPortInference::~PPortInference()
{
}
 
void PPortInference::Start()
{
    m_logger.LogVerbose() << "PPortInference::Start";
    
    // construct skeleton
    ara::core::InstanceSpecifier specifier{"Inference/AA/PPortInference"};
    m_interface = std::make_unique<deepracer::service::inference::skeleton::SvInfereceSkeletonImpl>(specifier);
    
    // offer service
    auto offer = m_interface->OfferService();
    if (offer.HasValue())
    {
        m_running = true;
        m_logger.LogVerbose() << "PPortInference::Start::OfferService";
    }
    else
    {
        m_running = false;
        m_logger.LogError() << "PPortInference::Start::OfferService::" << offer.Error().Message();
    }
}
 
void PPortInference::Terminate()
{
    m_logger.LogVerbose() << "PPortInference::Terminate";
    
    // stop port
    m_running = false;
    
    // stop offer service
    m_interface->StopOfferService();
    m_logger.LogVerbose() << "PPortInference::Terminate::StopOfferService";
}
 
void PPortInference::WriteDataInfEvent(const deepracer::service::inference::skeleton::events::InfEvent::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_InfEventData = data;
}
 
void PPortInference::SendEventInfEventCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            
            auto send = m_interface->InfEvent.Send(m_InfEventData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "PPortInference::SendEventInfEventCyclic::Send";
            }
            else
            {
                m_logger.LogError() << "PPortInference::SendEventInfEventCyclic::Send::" << send.Error().Message();
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void PPortInference::SendEventInfEventTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    auto send = m_interface->InfEvent.Send(m_InfEventData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPortInference::SendEventInfEventTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPortInference::SendEventInfEventTriggered::Send::" << send.Error().Message();
    }
}
 
void PPortInference::SendEventInfEventTriggered(const deepracer::service::inference::skeleton::events::InfEvent::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_InfEventData = data;
    auto send = m_interface->InfEvent.Send(m_InfEventData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPortInference::SendEventInfEventTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPortInference::SendEventInfEventTriggered::Send::" << send.Error().Message();
    }
}
 
} /// namespace port
} /// namespace aa
} /// namespace inference
 
/// EOF