///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : rportsensorfusion.cpp
/// SOFTWARE COMPONENT NAME           : RPortSensorFusion
/// GENERATED DATE                    : 2024-11-22 14:30:35
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "inference/aa/port/rportsensorfusion.h"
 
namespace inference
{
namespace aa
{
namespace port
{
 
RPortSensorFusion::RPortSensorFusion()
    : m_logger(ara::log::CreateLogger("INFE", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_found{false}
    , m_receiverSFEvent{nullptr}
{
}
 
RPortSensorFusion::~RPortSensorFusion()
{
}
 
void RPortSensorFusion::Start()
{
    m_logger.LogVerbose() << "RPortSensorFusion::Start";
    
    // regist callback
    ara::core::InstanceSpecifier specifier{"Inference/AA/RPortSensorFusion"};
    auto handler = [this](ara::com::ServiceHandleContainer<deepracer::service::sensorfusion::proxy::SvSensorFusionProxy::HandleType> handles,
                          ara::com::FindServiceHandle findHandle) {
        this->Find(handles, findHandle);
    };
    
    // find service
    auto find = deepracer::service::sensorfusion::proxy::SvSensorFusionProxy::StartFindService(handler, specifier);
    if (find.HasValue())
    {
        m_logger.LogVerbose() << "RPortSensorFusion::Start::StartFindService";
    }
    else
    {
        m_logger.LogError() << "RPortSensorFusion::Start::StartFindService::" << find.Error().Message();
    }
    
    // run port
    m_running = true;
}
 
void RPortSensorFusion::Terminate()
{
    m_logger.LogVerbose() << "RPortSensorFusion::Terminate";
    
    // stop port
    m_running = false;
    
    // clear service proxy
    if (m_interface)
    {
        // stop subscribe
        StopSubscribeSFEvent();
        
        // stop find service
        m_interface->StopFindService(*m_findHandle);
        m_found = false;
        
        m_logger.LogVerbose() << "RPortSensorFusion::Terminate::StopFindService";
    }
}
 
void RPortSensorFusion::Find(ara::com::ServiceHandleContainer<deepracer::service::sensorfusion::proxy::SvSensorFusionProxy::HandleType> handles, ara::com::FindServiceHandle findHandle)
{
    // check finding handles
    if (handles.empty())
    {
        m_logger.LogVerbose() << "RPortSensorFusion::Find::Service Instances not found";
        return;
    }
    else
    {
        for (auto& handle : handles)
        {
            m_logger.LogVerbose() << "RPortSensorFusion::Find::Searched Instance::ServiceId =" << 
                                     handle.GetServiceHandle().serviceId << 
                                     ", InstanceId =" << 
                                     handle.GetServiceHandle().instanceId;
        }
    }
    
    // create proxy
    if (m_interface)
    {
        m_logger.LogVerbose() << "RPortSensorFusion::Find::Proxy is already running";
    }
    else
    {
        m_logger.LogVerbose() << "RPortSensorFusion::Find::Using Instance::ServiceId =" << 
                                 handles[0].GetServiceHandle().serviceId << 
                                 ", InstanceId =" << 
                                 handles[0].GetServiceHandle().instanceId;
        m_interface = std::make_unique<deepracer::service::sensorfusion::proxy::SvSensorFusionProxy>(handles[0]);
        m_findHandle = std::make_unique<ara::com::FindServiceHandle>(findHandle);
        m_found = true;
        
        // subscribe events
        SubscribeSFEvent();
    }
}
 
void RPortSensorFusion::SubscribeSFEvent()
{
    if (m_found)
    {
        // regist receiver handler
        // if you want to enable it, please uncomment below code
        // RegistReceiverSFEvent();
        
        // request subscribe
        auto subscribe = m_interface->SFEvent.Subscribe(1);
        if (subscribe.HasValue())
        {
            m_logger.LogVerbose() << "RPortSensorFusion::SubscribeSFEvent::Subscribed";
        }
        else
        {
            m_logger.LogError() << "RPortSensorFusion::SubscribeSFEvent::" << subscribe.Error().Message();
        }
    }
}
 
void RPortSensorFusion::StopSubscribeSFEvent()
{
    if (m_found)
    {
        // request stop subscribe
        m_interface->SFEvent.Unsubscribe();
        m_logger.LogVerbose() << "RPortSensorFusion::StopSubscribeSFEvent::Unsubscribed";
    }
}
 
void RPortSensorFusion::RegistReceiverSFEvent()
{
    if (m_found)
    {
        // set callback
        auto receiver = [this]() -> void {
            return ReceiveEventSFEventTriggered();
        };
        
        // regist callback
        auto callback = m_interface->SFEvent.SetReceiveHandler(receiver);
        if (callback.HasValue())
        {
            m_logger.LogVerbose() << "RPortSensorFusion::RegistReceiverSFEvent::SetReceiveHandler";
        }
        else
        {
            m_logger.LogError() << "RPortSensorFusion::RegistReceiverSFEvent::SetReceiveHandler::" << callback.Error().Message();
        }
    }
}
 
void RPortSensorFusion::ReceiveEventSFEventTriggered()
{
    if (m_found)
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        
        if (m_interface->SFEvent.GetSubscriptionState() == ara::com::SubscriptionState::kSubscribed)
        {
            auto recv = std::make_unique<ara::core::Result<size_t>>(m_interface->SFEvent.GetNewSamples([&](auto samplePtr) {
                RPortSensorFusion::ReadDataSFEvent(std::move(samplePtr));
            }));
            if (recv->HasValue())
            {
                m_logger.LogVerbose() << "RPortSensorFusion::ReceiveEventSFEvent::GetNewSamples::" << recv->Value();
            }
            else
            {
                m_logger.LogError() << "RPortSensorFusion::ReceiveEventSFEvent::GetNewSamples::" << recv->Error().Message();
            }
        }
    }
}
 
void RPortSensorFusion::ReceiveEventSFEventCyclic()
{
    while (m_running)
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        
        if (m_found)
        {
            if (m_interface->SFEvent.GetSubscriptionState() == ara::com::SubscriptionState::kSubscribed)
            {
                auto recv = std::make_unique<ara::core::Result<size_t>>(m_interface->SFEvent.GetNewSamples([&](auto samplePtr) {
                    RPortSensorFusion::ReadDataSFEvent(std::move(samplePtr));
                }));
                if (recv->HasValue())
                {
                    m_logger.LogVerbose() << "RPortSensorFusion::ReceiveEventSFEvent::GetNewSamples::" << recv->Value();
                }
                else
                {
                    m_logger.LogError() << "RPortSensorFusion::ReceiveEventSFEvent::GetNewSamples::" << recv->Error().Message();
                }
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void RPortSensorFusion::ReadDataSFEvent(ara::com::SamplePtr<deepracer::service::sensorfusion::proxy::events::SFEvent::SampleType const> samplePtr)
{
    auto data = *samplePtr.Get();
    if (m_receiverSFEvent)
    {
        m_receiverSFEvent(data);
    }
}
 
void RPortSensorFusion::RegistEventHandlerSFEvent(std::function<void(const deepracer::service::sensorfusion::proxy::events::SFEvent::SampleType&)> handler)
{
    m_receiverSFEvent = handler;
}
 
} /// namespace port
} /// namespace aa
} /// namespace inference
 
/// EOF