///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : pportsensorfusion.h
/// SOFTWARE COMPONENT NAME           : PPortSensorFusion
/// GENERATED DATE                    : 2024-11-22 14:30:35
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_SENSORFUSION_AA_PPORTSENSORFUSION_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_SENSORFUSION_AA_PPORTSENSORFUSION_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "deepracer/service/sensorfusion/svsensorfusion_skeleton.h"
 
#include "ara/log/logger.h"
 
#include <mutex>
#include <thread>
 
namespace deepracer
{
namespace service
{
namespace sensorfusion
{
namespace skeleton
{
 
class SvSensorFusionSkeletonImpl : public SvSensorFusionSkeleton
{
public:
    /// @brief Constructor
    SvSensorFusionSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent);

private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;

};
 
} /// namespace skeleton
} /// namespace sensorfusion
} /// namespace service
} /// namespace deepracer

namespace sensorfusion
{
namespace aa
{
namespace port
{
 
class PPortSensorFusion
{
public:
    /// @brief Constructor
    PPortSensorFusion();
    
    /// @brief Destructor
    ~PPortSensorFusion();
    
    /// @brief Start port
    void Start();
    
    /// @brief Terminate port
    void Terminate();
    
    /// @brief Write event data to buffer, SFEvent
    void WriteDataSFEvent(const deepracer::service::sensorfusion::skeleton::events::SFEvent::SampleType& data);
     
    /// @brief Send event cyclic from buffer data, SFEvent
    void SendEventSFEventCyclic();
     
    /// @brief Send event directly from buffer data, SFEvent
    void SendEventSFEventTriggered();
     
    /// @brief Send event directly with argument, SFEvent
    void SendEventSFEventTriggered(const deepracer::service::sensorfusion::skeleton::events::SFEvent::SampleType& data);
     
private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    /// @brief Flag of port status
    bool m_running;
    
    /// @brief Mutex for this port
    std::mutex m_mutex;
    
    /// @brief AUTOSAR Port Interface
    std::unique_ptr<deepracer::service::sensorfusion::skeleton::SvSensorFusionSkeletonImpl> m_interface;
    
    /// @brief Data for event, SFEvent
    deepracer::service::sensorfusion::skeleton::events::SFEvent::SampleType m_SFEventData;
};
 
} /// namespace port
} /// namespace aa
} /// namespace sensorfusion
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_SENSORFUSION_AA_PPORTSENSORFUSION_H