///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : rportlidar.h
/// SOFTWARE COMPONENT NAME           : RPortLidar
/// GENERATED DATE                    : 2024-11-22 14:30:35
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_SENSORFUSION_AA_RPORTLIDAR_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_SENSORFUSION_AA_RPORTLIDAR_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "deepracer/service/lidar/svlidar_proxy.h"
 
#include "ara/log/logger.h"
 
#include <mutex>
#include <thread>
 
namespace sensorfusion
{
namespace aa
{
namespace port
{
 
class RPortLidar
{
public:
    /// @brief Constructor
    RPortLidar();
    
    /// @brief Destructor
    ~RPortLidar();
    
    /// @brief Start port
    void Start();
    
    /// @brief Terminate port
    void Terminate();
    
    /// @brief Subscribe event, LidEvent
    void SubscribeLidEvent();
     
    /// @brief Stop event subscription, LidEvent
    void StopSubscribeLidEvent();
     
    /// @brief Event receive handler, LidEvent
    void ReceiveEventLidEventTriggered();
     
    /// @brief Event receive handler, LidEvent
    void ReceiveEventLidEventCyclic();
     
    /// @brief Read event data, LidEvent
    void ReadDataLidEvent(ara::com::SamplePtr<deepracer::service::lidar::proxy::events::LidEvent::SampleType const> samplePtr);
     
    /// @brief Regist callback from software component
    void RegistEventHandlerLidEvent(std::function<void(const deepracer::service::lidar::proxy::events::LidEvent::SampleType&)> handler);

private:
    /// @brief Callback for find service
    void Find(ara::com::ServiceHandleContainer<deepracer::service::lidar::proxy::SvLidarProxy::HandleType> handles,
              ara::com::FindServiceHandle findHandle);
    
    /// @brief Callback for event receiver, LidEvent
    void RegistReceiverLidEvent();

private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    /// @brief Flag of port status
    bool m_running;
    
    /// @brief Flag of find service status
    bool m_found;
    
    /// @brief Mutex for this port
    std::mutex m_mutex; 
    
    /// @brief AUTOSAR Port Interface
    std::unique_ptr<deepracer::service::lidar::proxy::SvLidarProxy> m_interface;
    
    /// @brief Find service handle
    std::unique_ptr<ara::com::FindServiceHandle> m_findHandle;
    
    /// @brief Callback from software component, LidEvent
    std::function<void(const deepracer::service::lidar::proxy::events::LidEvent::SampleType&)> m_receiverLidEvent;

};
 
} /// namespace port
} /// namespace aa
} /// namespace sensorfusion
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_SENSORFUSION_AA_RPORTLIDAR_H