///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : impl_type_sensorfusion.h
/// IMPLEMENTATION DATA TYPE NAME     : SensorFusion
/// GENERATED DATE                    : 2024-12-03 10:27:51
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_ARA_COM_GEN_CPP_IMPL_TYPE_SENSORFUSION_H
#define PARA_ARA_COM_GEN_CPP_IMPL_TYPE_SENSORFUSION_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_00402}
#include <ara/core/structure.h>
#include "deepracer/sensorfusiondata/impl_type_sensorfusiondata.h"
#include "deepracer/timestamp/impl_type_timestamp.h"
#include "deepracer/vehiclemode/impl_type_vehiclemode.h"
/// @uptrace{SWS_CM_10375}
namespace deepracer
{
namespace serviceinterfacefusion
{
struct SensorFusion
{
    deepracer::sensorfusiondata::SensorFusionData data;
    deepracer::timestamp::Timestamp timestamp;
    deepracer::vehiclemode::VehicleMode vehiclemode;
    PARA_STRUCTURE(SensorFusion, data, timestamp, vehiclemode);
};
} /// namespace serviceinterfacefusion
} /// namespace deepracer
#endif /// PARA_ARA_COM_GEN_CPP_IMPL_TYPE_SENSORFUSION_H