///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : rportcamera.h
/// SOFTWARE COMPONENT NAME           : RPortCamera
/// GENERATED DATE                    : 2024-12-03 10:27:58
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_SENSORFUSION_AA_RPORTCAMERA_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_SENSORFUSION_AA_RPORTCAMERA_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "deepracer/service/camera/svcamera_proxy.h"
 
#include "ara/log/logger.h"
 
#include <mutex>
#include <thread>
 
namespace sensorfusion
{
namespace aa
{
namespace port
{
 
class RPortCamera
{
public:
    /// @brief Constructor
    RPortCamera();
    
    /// @brief Destructor
    ~RPortCamera();
    
    /// @brief Start port
    void Start();
    
    /// @brief Terminate port
    void Terminate();
    
    /// @brief Subscribe event, CamEvent
    void SubscribeCamEvent();
     
    /// @brief Stop event subscription, CamEvent
    void StopSubscribeCamEvent();
     
    /// @brief Event receive handler, CamEvent
    void ReceiveEventCamEventTriggered();
     
    /// @brief Event receive handler, CamEvent
    void ReceiveEventCamEventCyclic();
     
    /// @brief Read event data, CamEvent
    void ReadDataCamEvent(ara::com::SamplePtr<deepracer::service::camera::proxy::events::CamEvent::SampleType const> samplePtr);

    void SetReceiveEventCamEventHandler(std::function<void(const deepracer::service::camera::proxy::events::CamEvent::SampleType&)> handler);
    
private:
    /// @brief Callback for find service
    void Find(ara::com::ServiceHandleContainer<deepracer::service::camera::proxy::SvCameraProxy::HandleType> handles,
              ara::com::FindServiceHandle findHandle);
    
    /// @brief Callback for event receiver, CamEvent
    void RegistReceiverCamEvent();
    
    
private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    /// @brief Flag of port status
    bool m_running;
    
    /// @brief Flag of find service status
    bool m_found;
    
    /// @brief Mutex for this port
    std::mutex m_mutex; 
    
    /// @brief AUTOSAR Port Interface
    std::shared_ptr<deepracer::service::camera::proxy::SvCameraProxy> m_interface;
    
    /// @brief Find service handle
    std::shared_ptr<ara::com::FindServiceHandle> m_findHandle;
    
    /// @brief Receive event handler
    std::function<void(const deepracer::service::camera::proxy::events::CamEvent::SampleType&)> m_receiveEventCamEventHandler;
};
 
} /// namespace port
} /// namespace aa
} /// namespace sensorfusion
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_SENSORFUSION_AA_RPORTCAMERA_H