///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : sensorfusion.cpp
/// SOFTWARE COMPONENT NAME           : SensorFusion
/// GENERATED DATE                    : 2024-11-22 14:30:35
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "sensorfusion/aa/sensorfusion.h"
 
namespace sensorfusion
{
namespace aa
{
 
SensorFusion::SensorFusion()
    : m_logger(ara::log::CreateLogger("SEFU", "SWC", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_workers(3)
{
}
 
SensorFusion::~SensorFusion()
{
}
 
bool SensorFusion::Initialize()
{
    m_logger.LogVerbose() << "SensorFusion::Initialize";
    
    bool init = true;
    
    m_PPortSensorFusion = std::make_unique<sensorfusion::aa::port::PPortSensorFusion>();
    m_RPortCamera = std::make_unique<sensorfusion::aa::port::RPortCamera>();
    m_RPortLidar = std::make_unique<sensorfusion::aa::port::RPortLidar>();
    
    // put your code for initialization
    
    return init;
}
 
void SensorFusion::Start()
{
    m_logger.LogVerbose() << "SensorFusion::Start";
    
    m_PPortSensorFusion->Start();
    m_RPortCamera->Start();
    m_RPortLidar->Start();
}
 
void SensorFusion::Terminate()
{
    m_logger.LogVerbose() << "SensorFusion::Terminate";
    
    // stop running
    m_running = false;
    
    m_PPortSensorFusion->Terminate();
    m_RPortCamera->Terminate();
    m_RPortLidar->Terminate();
}
 
void SensorFusion::Run()
{
    m_logger.LogVerbose() << "SensorFusion::Run";
    
    // start running
    m_running = true;
    
    m_workers.Async([this] { m_PPortSensorFusion->SendEventSFEventCyclic(); });
    m_workers.Async([this] { m_RPortCamera->ReceiveEventCamEventCyclic(); });
    m_workers.Async([this] { m_RPortLidar->ReceiveEventLidEventCyclic(); });
    
    m_workers.Wait();
}
 
} /// namespace aa
} /// namespace sensorfusion
