///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : navigation.h
/// SOFTWARE COMPONENT NAME           : Navigation
/// GENERATED DATE                    : 2024-11-22 14:30:35
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_NAVIGATION_AA_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_NAVIGATION_AA_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "navigation/aa/port/pportnavigation.h"
#include "navigation/aa/port/rportinference.h"
 
#include "para/swc/port_pool.h"
 
namespace navigation
{
namespace aa
{
 
class Navigation
{
public:
    /// @brief Constructor
    Navigation();
    
    /// @brief Destructor
    ~Navigation();
    
    /// @brief Initialize software component
    bool Initialize();
    
    /// @brief Start software component
    void Start();
    
    /// @brief Terminate software component
    void Terminate();
    
    /// @brief Run software component
    void Run();
    
private:
    /// @brief Running status of software component
    bool m_running;
    
    /// @brief Pool of port
    ::para::swc::PortPool m_workers;
    
    /// @brief Logger for software component
    ara::log::Logger& m_logger;
    
    /// @brief Instance of Port {Navigation.PPortNavigation}
    std::unique_ptr<navigation::aa::port::PPortNavigation> m_PPortNavigation;
    
    /// @brief Instance of Port {Navigation.RPortInference}
    std::unique_ptr<navigation::aa::port::RPortInference> m_RPortInference;
};
 
} /// namespace aa
} /// namespace navigation
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_NAVIGATION_AA_H