///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : pportinference.h
/// SOFTWARE COMPONENT NAME           : PPortInference
/// GENERATED DATE                    : 2024-12-03 10:27:56
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_INFERENCE_AA_PPORTINFERENCE_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_INFERENCE_AA_PPORTINFERENCE_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "deepracer/service/inference/svinferece_skeleton.h"
 
#include "ara/log/logger.h"
 
#include <mutex>
#include <thread>
 
namespace deepracer
{
namespace service
{
namespace inference
{
namespace skeleton
{
 
class SvInfereceSkeletonImpl : public SvInfereceSkeleton
{
public:
    /// @brief Constructor
    SvInfereceSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent);
    
    
    
private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    
};
 
} /// namespace skeleton
} /// namespace inference
} /// namespace service
} /// namespace deepracer

namespace inference
{
namespace aa
{
namespace port
{
 
class PPortInference
{
public:
    /// @brief Constructor
    PPortInference();
    
    /// @brief Destructor
    ~PPortInference();
    
    /// @brief Start port
    void Start();
    
    /// @brief Terminate port
    void Terminate();
    
    /// @brief Write event data to buffer, InfEvent
    void WriteDataInfEvent(const deepracer::service::inference::skeleton::events::InfEvent::SampleType& data);
     
    /// @brief Send event cyclic from buffer data, InfEvent
    void SendEventInfEventCyclic();
     
    /// @brief Send event directly from buffer data, InfEvent
    void SendEventInfEventTriggered();
     
    /// @brief Send event directly with argument, InfEvent
    void SendEventInfEventTriggered(const deepracer::service::inference::skeleton::events::InfEvent::SampleType& data);
     
private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    /// @brief Flag of port status
    bool m_running;
    
    /// @brief Mutex for this port
    std::mutex m_mutex;
    
    /// @brief AUTOSAR Port Interface
    std::shared_ptr<deepracer::service::inference::skeleton::SvInfereceSkeletonImpl> m_interface;
    
    /// @brief Data for event, InfEvent
    deepracer::service::inference::skeleton::events::InfEvent::SampleType m_InfEventData;
};
 
} /// namespace port
} /// namespace aa
} /// namespace inference
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_INFERENCE_AA_PPORTINFERENCE_H