///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : rportinference.h
/// SOFTWARE COMPONENT NAME           : RPortInference
/// GENERATED DATE                    : 2024-12-03 10:27:57
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_NAVIGATION_AA_RPORTINFERENCE_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_NAVIGATION_AA_RPORTINFERENCE_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "deepracer/service/inference/svinferece_proxy.h"
 
#include "ara/log/logger.h"
 
#include <mutex>
#include <thread>
 
namespace navigation
{
namespace aa
{
namespace port
{
 
class RPortInference
{
public:
    /// @brief Constructor
    RPortInference();
    
    /// @brief Destructor
    ~RPortInference();
    
    /// @brief Start port
    void Start();
    
    /// @brief Terminate port
    void Terminate();
    
    /// @brief Subscribe event, InfEvent
    void SubscribeInfEvent();
     
    /// @brief Stop event subscription, InfEvent
    void StopSubscribeInfEvent();
     
    /// @brief Event receive handler, InfEvent
    void ReceiveEventInfEventTriggered();
     
    /// @brief Event receive handler, InfEvent
    void ReceiveEventInfEventCyclic();
     
    /// @brief Read event data, InfEvent
    void ReadDataInfEvent(ara::com::SamplePtr<deepracer::service::inference::proxy::events::InfEvent::SampleType const> samplePtr);

    void SetReceiveEventInfEventHandler(std::function<void(const deepracer::service::inference::proxy::events::InfEvent::SampleType&)> handler);
    
private:
    /// @brief Callback for find service
    void Find(ara::com::ServiceHandleContainer<deepracer::service::inference::proxy::SvInfereceProxy::HandleType> handles,
              ara::com::FindServiceHandle findHandle);
    
    /// @brief Callback for event receiver, InfEvent
    void RegistReceiverInfEvent();
    
    
private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    /// @brief Flag of port status
    bool m_running;
    
    /// @brief Flag of find service status
    bool m_found;
    
    /// @brief Mutex for this port
    std::mutex m_mutex; 
    
    /// @brief AUTOSAR Port Interface
    std::shared_ptr<deepracer::service::inference::proxy::SvInfereceProxy> m_interface;
    
    /// @brief Find service handle
    std::shared_ptr<ara::com::FindServiceHandle> m_findHandle;
    
    /// @brief Receive event handler
    std::function<void(const deepracer::service::inference::proxy::events::InfEvent::SampleType&)> m_receiveEventInfEventHandler;
};
 
} /// namespace port
} /// namespace aa
} /// namespace navigation
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_NAVIGATION_AA_RPORTINFERENCE_H