///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : pportnavigation.h
/// SOFTWARE COMPONENT NAME           : PPortNavigation
/// GENERATED DATE                    : 2024-11-22 14:30:35
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_NAVIGATION_AA_PPORTNAVIGATION_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_NAVIGATION_AA_PPORTNAVIGATION_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "deepracer/service/navigation/svnavigation_skeleton.h"
 
#include "ara/log/logger.h"
 
#include <mutex>
#include <thread>
 
namespace deepracer
{
namespace service
{
namespace navigation
{
namespace skeleton
{
 
class SvNavigationSkeletonImpl : public SvNavigationSkeleton
{
public:
    /// @brief Constructor
    SvNavigationSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent);

private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;

};
 
} /// namespace skeleton
} /// namespace navigation
} /// namespace service
} /// namespace deepracer

namespace navigation
{
namespace aa
{
namespace port
{
 
class PPortNavigation
{
public:
    /// @brief Constructor
    PPortNavigation();
    
    /// @brief Destructor
    ~PPortNavigation();
    
    /// @brief Start port
    void Start();
    
    /// @brief Terminate port
    void Terminate();
    
    /// @brief Write event data to buffer, NavEvent
    void WriteDataNavEvent(const deepracer::service::navigation::skeleton::events::NavEvent::SampleType& data);
     
    /// @brief Send event cyclic from buffer data, NavEvent
    void SendEventNavEventCyclic();
     
    /// @brief Send event directly from buffer data, NavEvent
    void SendEventNavEventTriggered();
     
    /// @brief Send event directly with argument, NavEvent
    void SendEventNavEventTriggered(const deepracer::service::navigation::skeleton::events::NavEvent::SampleType& data);
     
private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    /// @brief Flag of port status
    bool m_running;
    
    /// @brief Mutex for this port
    std::mutex m_mutex;
    
    /// @brief AUTOSAR Port Interface
    std::unique_ptr<deepracer::service::navigation::skeleton::SvNavigationSkeletonImpl> m_interface;
    
    /// @brief Data for event, NavEvent
    deepracer::service::navigation::skeleton::events::NavEvent::SampleType m_NavEventData;
};
 
} /// namespace port
} /// namespace aa
} /// namespace navigation
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_NAVIGATION_AA_PPORTNAVIGATION_H