///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : rportsensorfusion.h
/// SOFTWARE COMPONENT NAME           : RPortSensorFusion
/// GENERATED DATE                    : 2024-11-22 14:30:35
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_INFERENCE_AA_RPORTSENSORFUSION_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_INFERENCE_AA_RPORTSENSORFUSION_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "deepracer/service/sensorfusion/svsensorfusion_proxy.h"
 
#include "ara/log/logger.h"
 
#include <mutex>
#include <thread>
 
namespace inference
{
namespace aa
{
namespace port
{
 
class RPortSensorFusion
{
public:
    /// @brief Constructor
    RPortSensorFusion();
    
    /// @brief Destructor
    ~RPortSensorFusion();
    
    /// @brief Start port
    void Start();
    
    /// @brief Terminate port
    void Terminate();
    
    /// @brief Subscribe event, SFEvent
    void SubscribeSFEvent();
     
    /// @brief Stop event subscription, SFEvent
    void StopSubscribeSFEvent();
     
    /// @brief Event receive handler, SFEvent
    void ReceiveEventSFEventTriggered();
     
    /// @brief Event receive handler, SFEvent
    void ReceiveEventSFEventCyclic();
     
    /// @brief Read event data, SFEvent
    void ReadDataSFEvent(ara::com::SamplePtr<deepracer::service::sensorfusion::proxy::events::SFEvent::SampleType const> samplePtr);
     
    /// @brief Regist callback from software component
    void RegistEventHandlerSFEvent(std::function<void(const deepracer::service::sensorfusion::proxy::events::SFEvent::SampleType&)> handler);

private:
    /// @brief Callback for find service
    void Find(ara::com::ServiceHandleContainer<deepracer::service::sensorfusion::proxy::SvSensorFusionProxy::HandleType> handles,
              ara::com::FindServiceHandle findHandle);
    
    /// @brief Callback for event receiver, SFEvent
    void RegistReceiverSFEvent();

private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    /// @brief Flag of port status
    bool m_running;
    
    /// @brief Flag of find service status
    bool m_found;
    
    /// @brief Mutex for this port
    std::mutex m_mutex; 
    
    /// @brief AUTOSAR Port Interface
    std::unique_ptr<deepracer::service::sensorfusion::proxy::SvSensorFusionProxy> m_interface;
    
    /// @brief Find service handle
    std::unique_ptr<ara::com::FindServiceHandle> m_findHandle;
    
    /// @brief Callback from software component, SFEvent
    std::function<void(const deepracer::service::sensorfusion::proxy::events::SFEvent::SampleType&)> m_receiverSFEvent;

};
 
} /// namespace port
} /// namespace aa
} /// namespace inference
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_INFERENCE_AA_RPORTSENSORFUSION_H