///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : inference.cpp
/// SOFTWARE COMPONENT NAME           : Inference
/// GENERATED DATE                    : 2024-11-22 14:30:35
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "inference/aa/inference.h"
 
namespace inference
{
namespace aa
{
 
Inference::Inference()
    : m_logger(ara::log::CreateLogger("INFE", "SWC", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_workers(2)
{
}
 
Inference::~Inference()
{
}
 
bool Inference::Initialize()
{
    m_logger.LogVerbose() << "Inference::Initialize";
    
    bool init = true;
    
    m_PPortInference = std::make_unique<inference::aa::port::PPortInference>();
    m_RPortSensorFusion = std::make_unique<inference::aa::port::RPortSensorFusion>();
    
    // put your code for initialization
    
    return init;
}
 
void Inference::Start()
{
    m_logger.LogVerbose() << "Inference::Start";
    
    m_PPortInference->Start();
    m_RPortSensorFusion->Start();
}
 
void Inference::Terminate()
{
    m_logger.LogVerbose() << "Inference::Terminate";
    
    // stop running
    m_running = false;
    
    m_PPortInference->Terminate();
    m_RPortSensorFusion->Terminate();
}
 
void Inference::Run()
{
    m_logger.LogVerbose() << "Inference::Run";
    
    // start running
    m_running = true;
    
    m_workers.Async([this] { m_PPortInference->SendEventInfEventCyclic(); });
    m_workers.Async([this] { m_RPortSensorFusion->ReceiveEventSFEventCyclic(); });
    
    m_workers.Wait();
}
 
} /// namespace aa
} /// namespace inference
