///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : pportsensorfusion.cpp
/// SOFTWARE COMPONENT NAME           : PPortSensorFusion
/// GENERATED DATE                    : 2024-11-22 14:30:35
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "sensorfusion/aa/port/pportsensorfusion.h"
 
namespace deepracer
{
namespace service
{
namespace sensorfusion
{
namespace skeleton
{
 
SvSensorFusionSkeletonImpl::SvSensorFusionSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode)
    : SvSensorFusionSkeleton(instanceSpec, mode)
    , m_logger(ara::log::CreateLogger("SEFU", "PORT", ara::log::LogLevel::kVerbose))
{
}
 
} /// namespace skeleton
} /// namespace sensorfusion
} /// namespace service
} /// namespace deepracer

namespace sensorfusion
{
namespace aa
{
namespace port
{
 
PPortSensorFusion::PPortSensorFusion()
    : m_logger(ara::log::CreateLogger("SEFU", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_SFEventData{0U}
{
}
 
PPortSensorFusion::~PPortSensorFusion()
{
}
 
void PPortSensorFusion::Start()
{
    m_logger.LogVerbose() << "PPortSensorFusion::Start";
    
    // construct skeleton
    ara::core::InstanceSpecifier specifier{"SensorFusion/AA/PPortSensorFusion"};
    m_interface = std::make_unique<deepracer::service::sensorfusion::skeleton::SvSensorFusionSkeletonImpl>(specifier);
    
    // offer service
    auto offer = m_interface->OfferService();
    if (offer.HasValue())
    {
        m_running = true;
        m_logger.LogVerbose() << "PPortSensorFusion::Start::OfferService";
    }
    else
    {
        m_running = false;
        m_logger.LogError() << "PPortSensorFusion::Start::OfferService::" << offer.Error().Message();
    }
}
 
void PPortSensorFusion::Terminate()
{
    m_logger.LogVerbose() << "PPortSensorFusion::Terminate";
    
    // stop port
    m_running = false;
    
    // stop offer service
    m_interface->StopOfferService();
    m_logger.LogVerbose() << "PPortSensorFusion::Terminate::StopOfferService";
}
 
void PPortSensorFusion::WriteDataSFEvent(const deepracer::service::sensorfusion::skeleton::events::SFEvent::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_SFEventData = data;
}
 
void PPortSensorFusion::SendEventSFEventCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            
            auto send = m_interface->SFEvent.Send(m_SFEventData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "PPortSensorFusion::SendEventSFEventCyclic::Send";
            }
            else
            {
                m_logger.LogError() << "PPortSensorFusion::SendEventSFEventCyclic::Send::" << send.Error().Message();
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void PPortSensorFusion::SendEventSFEventTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    auto send = m_interface->SFEvent.Send(m_SFEventData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPortSensorFusion::SendEventSFEventTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPortSensorFusion::SendEventSFEventTriggered::Send::" << send.Error().Message();
    }
}
 
void PPortSensorFusion::SendEventSFEventTriggered(const deepracer::service::sensorfusion::skeleton::events::SFEvent::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_SFEventData = data;
    auto send = m_interface->SFEvent.Send(m_SFEventData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPortSensorFusion::SendEventSFEventTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPortSensorFusion::SendEventSFEventTriggered::Send::" << send.Error().Message();
    }
}
 
} /// namespace port
} /// namespace aa
} /// namespace sensorfusion
 
/// EOF