///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : rportlidar.cpp
/// SOFTWARE COMPONENT NAME           : RPortLidar
/// GENERATED DATE                    : 2024-11-22 14:30:35
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "sensorfusion/aa/port/rportlidar.h"
 
namespace sensorfusion
{
namespace aa
{
namespace port
{
 
RPortLidar::RPortLidar()
    : m_logger(ara::log::CreateLogger("SEFU", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_found{false}
    , m_receiverLidEvent{nullptr}
{
}
 
RPortLidar::~RPortLidar()
{
}
 
void RPortLidar::Start()
{
    m_logger.LogVerbose() << "RPortLidar::Start";
    
    // regist callback
    ara::core::InstanceSpecifier specifier{"SensorFusion/AA/RPortLidar"};
    auto handler = [this](ara::com::ServiceHandleContainer<deepracer::service::lidar::proxy::SvLidarProxy::HandleType> handles,
                          ara::com::FindServiceHandle findHandle) {
        this->Find(handles, findHandle);
    };
    
    // find service
    auto find = deepracer::service::lidar::proxy::SvLidarProxy::StartFindService(handler, specifier);
    if (find.HasValue())
    {
        m_logger.LogVerbose() << "RPortLidar::Start::StartFindService";
    }
    else
    {
        m_logger.LogError() << "RPortLidar::Start::StartFindService::" << find.Error().Message();
    }
    
    // run port
    m_running = true;
}
 
void RPortLidar::Terminate()
{
    m_logger.LogVerbose() << "RPortLidar::Terminate";
    
    // stop port
    m_running = false;
    
    // clear service proxy
    if (m_interface)
    {
        // stop subscribe
        StopSubscribeLidEvent();
        
        // stop find service
        m_interface->StopFindService(*m_findHandle);
        m_found = false;
        
        m_logger.LogVerbose() << "RPortLidar::Terminate::StopFindService";
    }
}
 
void RPortLidar::Find(ara::com::ServiceHandleContainer<deepracer::service::lidar::proxy::SvLidarProxy::HandleType> handles, ara::com::FindServiceHandle findHandle)
{
    // check finding handles
    if (handles.empty())
    {
        m_logger.LogVerbose() << "RPortLidar::Find::Service Instances not found";
        return;
    }
    else
    {
        for (auto& handle : handles)
        {
            m_logger.LogVerbose() << "RPortLidar::Find::Searched Instance::ServiceId =" << 
                                     handle.GetServiceHandle().serviceId << 
                                     ", InstanceId =" << 
                                     handle.GetServiceHandle().instanceId;
        }
    }
    
    // create proxy
    if (m_interface)
    {
        m_logger.LogVerbose() << "RPortLidar::Find::Proxy is already running";
    }
    else
    {
        m_logger.LogVerbose() << "RPortLidar::Find::Using Instance::ServiceId =" << 
                                 handles[0].GetServiceHandle().serviceId << 
                                 ", InstanceId =" << 
                                 handles[0].GetServiceHandle().instanceId;
        m_interface = std::make_unique<deepracer::service::lidar::proxy::SvLidarProxy>(handles[0]);
        m_findHandle = std::make_unique<ara::com::FindServiceHandle>(findHandle);
        m_found = true;
        
        // subscribe events
        SubscribeLidEvent();
    }
}
 
void RPortLidar::SubscribeLidEvent()
{
    if (m_found)
    {
        // regist receiver handler
        // if you want to enable it, please uncomment below code
        // RegistReceiverLidEvent();
        
        // request subscribe
        auto subscribe = m_interface->LidEvent.Subscribe(1);
        if (subscribe.HasValue())
        {
            m_logger.LogVerbose() << "RPortLidar::SubscribeLidEvent::Subscribed";
        }
        else
        {
            m_logger.LogError() << "RPortLidar::SubscribeLidEvent::" << subscribe.Error().Message();
        }
    }
}
 
void RPortLidar::StopSubscribeLidEvent()
{
    if (m_found)
    {
        // request stop subscribe
        m_interface->LidEvent.Unsubscribe();
        m_logger.LogVerbose() << "RPortLidar::StopSubscribeLidEvent::Unsubscribed";
    }
}
 
void RPortLidar::RegistReceiverLidEvent()
{
    if (m_found)
    {
        // set callback
        auto receiver = [this]() -> void {
            return ReceiveEventLidEventTriggered();
        };
        
        // regist callback
        auto callback = m_interface->LidEvent.SetReceiveHandler(receiver);
        if (callback.HasValue())
        {
            m_logger.LogVerbose() << "RPortLidar::RegistReceiverLidEvent::SetReceiveHandler";
        }
        else
        {
            m_logger.LogError() << "RPortLidar::RegistReceiverLidEvent::SetReceiveHandler::" << callback.Error().Message();
        }
    }
}
 
void RPortLidar::ReceiveEventLidEventTriggered()
{
    if (m_found)
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        
        if (m_interface->LidEvent.GetSubscriptionState() == ara::com::SubscriptionState::kSubscribed)
        {
            auto recv = std::make_unique<ara::core::Result<size_t>>(m_interface->LidEvent.GetNewSamples([&](auto samplePtr) {
                RPortLidar::ReadDataLidEvent(std::move(samplePtr));
            }));
            if (recv->HasValue())
            {
                m_logger.LogVerbose() << "RPortLidar::ReceiveEventLidEvent::GetNewSamples::" << recv->Value();
            }
            else
            {
                m_logger.LogError() << "RPortLidar::ReceiveEventLidEvent::GetNewSamples::" << recv->Error().Message();
            }
        }
    }
}
 
void RPortLidar::ReceiveEventLidEventCyclic()
{
    while (m_running)
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        
        if (m_found)
        {
            if (m_interface->LidEvent.GetSubscriptionState() == ara::com::SubscriptionState::kSubscribed)
            {
                auto recv = std::make_unique<ara::core::Result<size_t>>(m_interface->LidEvent.GetNewSamples([&](auto samplePtr) {
                    RPortLidar::ReadDataLidEvent(std::move(samplePtr));
                }));
                if (recv->HasValue())
                {
                    m_logger.LogVerbose() << "RPortLidar::ReceiveEventLidEvent::GetNewSamples::" << recv->Value();
                }
                else
                {
                    m_logger.LogError() << "RPortLidar::ReceiveEventLidEvent::GetNewSamples::" << recv->Error().Message();
                }
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void RPortLidar::ReadDataLidEvent(ara::com::SamplePtr<deepracer::service::lidar::proxy::events::LidEvent::SampleType const> samplePtr)
{
    auto data = *samplePtr.Get();
    if (m_receiverLidEvent)
    {
        m_receiverLidEvent(data);
    }
}
 
void RPortLidar::RegistEventHandlerLidEvent(std::function<void(const deepracer::service::lidar::proxy::events::LidEvent::SampleType&)> handler)
{
    m_receiverLidEvent = handler;
}
 
} /// namespace port
} /// namespace aa
} /// namespace sensorfusion
 
/// EOF