///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : rportnavigation.cpp
/// SOFTWARE COMPONENT NAME           : RPortNavigation
/// GENERATED DATE                    : 2024-11-22 14:30:35
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "servo/aa/port/rportnavigation.h"
 
namespace servo
{
namespace aa
{
namespace port
{
 
RPortNavigation::RPortNavigation()
    : m_logger(ara::log::CreateLogger("SERV", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_found{false}
    , m_receiverNavEvent{nullptr}
{
}
 
RPortNavigation::~RPortNavigation()
{
}
 
void RPortNavigation::Start()
{
    m_logger.LogVerbose() << "RPortNavigation::Start";
    
    // regist callback
    ara::core::InstanceSpecifier specifier{"Servo/AA/RPortNavigation"};
    auto handler = [this](ara::com::ServiceHandleContainer<deepracer::service::navigation::proxy::SvNavigationProxy::HandleType> handles,
                          ara::com::FindServiceHandle findHandle) {
        this->Find(handles, findHandle);
    };
    
    // find service
    auto find = deepracer::service::navigation::proxy::SvNavigationProxy::StartFindService(handler, specifier);
    if (find.HasValue())
    {
        m_logger.LogVerbose() << "RPortNavigation::Start::StartFindService";
    }
    else
    {
        m_logger.LogError() << "RPortNavigation::Start::StartFindService::" << find.Error().Message();
    }
    
    // run port
    m_running = true;
}
 
void RPortNavigation::Terminate()
{
    m_logger.LogVerbose() << "RPortNavigation::Terminate";
    
    // stop port
    m_running = false;
    
    // clear service proxy
    if (m_interface)
    {
        // stop subscribe
        StopSubscribeNavEvent();
        
        // stop find service
        m_interface->StopFindService(*m_findHandle);
        m_found = false;
        
        m_logger.LogVerbose() << "RPortNavigation::Terminate::StopFindService";
    }
}
 
void RPortNavigation::Find(ara::com::ServiceHandleContainer<deepracer::service::navigation::proxy::SvNavigationProxy::HandleType> handles, ara::com::FindServiceHandle findHandle)
{
    // check finding handles
    if (handles.empty())
    {
        m_logger.LogVerbose() << "RPortNavigation::Find::Service Instances not found";
        return;
    }
    else
    {
        for (auto& handle : handles)
        {
            m_logger.LogVerbose() << "RPortNavigation::Find::Searched Instance::ServiceId =" << 
                                     handle.GetServiceHandle().serviceId << 
                                     ", InstanceId =" << 
                                     handle.GetServiceHandle().instanceId;
        }
    }
    
    // create proxy
    if (m_interface)
    {
        m_logger.LogVerbose() << "RPortNavigation::Find::Proxy is already running";
    }
    else
    {
        m_logger.LogVerbose() << "RPortNavigation::Find::Using Instance::ServiceId =" << 
                                 handles[0].GetServiceHandle().serviceId << 
                                 ", InstanceId =" << 
                                 handles[0].GetServiceHandle().instanceId;
        m_interface = std::make_unique<deepracer::service::navigation::proxy::SvNavigationProxy>(handles[0]);
        m_findHandle = std::make_unique<ara::com::FindServiceHandle>(findHandle);
        m_found = true;
        
        // subscribe events
        SubscribeNavEvent();
    }
}
 
void RPortNavigation::SubscribeNavEvent()
{
    if (m_found)
    {
        // regist receiver handler
        // if you want to enable it, please uncomment below code
        // RegistReceiverNavEvent();
        
        // request subscribe
        auto subscribe = m_interface->NavEvent.Subscribe(1);
        if (subscribe.HasValue())
        {
            m_logger.LogVerbose() << "RPortNavigation::SubscribeNavEvent::Subscribed";
        }
        else
        {
            m_logger.LogError() << "RPortNavigation::SubscribeNavEvent::" << subscribe.Error().Message();
        }
    }
}
 
void RPortNavigation::StopSubscribeNavEvent()
{
    if (m_found)
    {
        // request stop subscribe
        m_interface->NavEvent.Unsubscribe();
        m_logger.LogVerbose() << "RPortNavigation::StopSubscribeNavEvent::Unsubscribed";
    }
}
 
void RPortNavigation::RegistReceiverNavEvent()
{
    if (m_found)
    {
        // set callback
        auto receiver = [this]() -> void {
            return ReceiveEventNavEventTriggered();
        };
        
        // regist callback
        auto callback = m_interface->NavEvent.SetReceiveHandler(receiver);
        if (callback.HasValue())
        {
            m_logger.LogVerbose() << "RPortNavigation::RegistReceiverNavEvent::SetReceiveHandler";
        }
        else
        {
            m_logger.LogError() << "RPortNavigation::RegistReceiverNavEvent::SetReceiveHandler::" << callback.Error().Message();
        }
    }
}
 
void RPortNavigation::ReceiveEventNavEventTriggered()
{
    if (m_found)
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        
        if (m_interface->NavEvent.GetSubscriptionState() == ara::com::SubscriptionState::kSubscribed)
        {
            auto recv = std::make_unique<ara::core::Result<size_t>>(m_interface->NavEvent.GetNewSamples([&](auto samplePtr) {
                RPortNavigation::ReadDataNavEvent(std::move(samplePtr));
            }));
            if (recv->HasValue())
            {
                m_logger.LogVerbose() << "RPortNavigation::ReceiveEventNavEvent::GetNewSamples::" << recv->Value();
            }
            else
            {
                m_logger.LogError() << "RPortNavigation::ReceiveEventNavEvent::GetNewSamples::" << recv->Error().Message();
            }
        }
    }
}
 
void RPortNavigation::ReceiveEventNavEventCyclic()
{
    while (m_running)
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        
        if (m_found)
        {
            if (m_interface->NavEvent.GetSubscriptionState() == ara::com::SubscriptionState::kSubscribed)
            {
                auto recv = std::make_unique<ara::core::Result<size_t>>(m_interface->NavEvent.GetNewSamples([&](auto samplePtr) {
                    RPortNavigation::ReadDataNavEvent(std::move(samplePtr));
                }));
                if (recv->HasValue())
                {
                    m_logger.LogVerbose() << "RPortNavigation::ReceiveEventNavEvent::GetNewSamples::" << recv->Value();
                }
                else
                {
                    m_logger.LogError() << "RPortNavigation::ReceiveEventNavEvent::GetNewSamples::" << recv->Error().Message();
                }
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void RPortNavigation::ReadDataNavEvent(ara::com::SamplePtr<deepracer::service::navigation::proxy::events::NavEvent::SampleType const> samplePtr)
{
    auto data = *samplePtr.Get();
    if (m_receiverNavEvent)
    {
        m_receiverNavEvent(data);
    }
}
 
void RPortNavigation::RegistEventHandlerNavEvent(std::function<void(const deepracer::service::navigation::proxy::events::NavEvent::SampleType&)> handler)
{
    m_receiverNavEvent = handler;
}
 
} /// namespace port
} /// namespace aa
} /// namespace servo
 
/// EOF