///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : lidar.cpp
/// SOFTWARE COMPONENT NAME           : Lidar
/// GENERATED DATE                    : 2024-11-22 14:30:35
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "lidar/aa/lidar.h"
 
namespace lidar
{
namespace aa
{
 
Lidar::Lidar()
    : m_logger(ara::log::CreateLogger("LID", "SWC", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_workers(1)
{
}
 
Lidar::~Lidar()
{
}
 
bool Lidar::Initialize()
{
    m_logger.LogVerbose() << "Lidar::Initialize";
    
    bool init = true;
    
    m_PPortLidar = std::make_unique<lidar::aa::port::PPortLidar>();
    
    // put your code for initialization
    
    return init;
}
 
void Lidar::Start()
{
    m_logger.LogVerbose() << "Lidar::Start";
    
    m_PPortLidar->Start();
}
 
void Lidar::Terminate()
{
    m_logger.LogVerbose() << "Lidar::Terminate";
    
    // stop running
    m_running = false;
    
    m_PPortLidar->Terminate();
}
 
void Lidar::Run()
{
    m_logger.LogVerbose() << "Lidar::Run";
    
    // start running
    m_running = true;
    
    m_workers.Async([this] { m_PPortLidar->SendEventLidEventCyclic(); });
    
    m_workers.Wait();
}
 
} /// namespace aa
} /// namespace lidar
