///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : pportlidar.h
/// SOFTWARE COMPONENT NAME           : PPortLidar
/// GENERATED DATE                    : 2024-11-22 14:30:35
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_LIDAR_AA_PPORTLIDAR_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_LIDAR_AA_PPORTLIDAR_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "deepracer/service/lidar/svlidar_skeleton.h"
 
#include "ara/log/logger.h"
 
#include <mutex>
#include <thread>
 
namespace deepracer
{
namespace service
{
namespace lidar
{
namespace skeleton
{
 
class SvLidarSkeletonImpl : public SvLidarSkeleton
{
public:
    /// @brief Constructor
    SvLidarSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent);

private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;

};
 
} /// namespace skeleton
} /// namespace lidar
} /// namespace service
} /// namespace deepracer

namespace lidar
{
namespace aa
{
namespace port
{
 
class PPortLidar
{
public:
    /// @brief Constructor
    PPortLidar();
    
    /// @brief Destructor
    ~PPortLidar();
    
    /// @brief Start port
    void Start();
    
    /// @brief Terminate port
    void Terminate();
    
    /// @brief Write event data to buffer, LidEvent
    void WriteDataLidEvent(const deepracer::service::lidar::skeleton::events::LidEvent::SampleType& data);
     
    /// @brief Send event cyclic from buffer data, LidEvent
    void SendEventLidEventCyclic();
     
    /// @brief Send event directly from buffer data, LidEvent
    void SendEventLidEventTriggered();
     
    /// @brief Send event directly with argument, LidEvent
    void SendEventLidEventTriggered(const deepracer::service::lidar::skeleton::events::LidEvent::SampleType& data);
     
private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    /// @brief Flag of port status
    bool m_running;
    
    /// @brief Mutex for this port
    std::mutex m_mutex;
    
    /// @brief AUTOSAR Port Interface
    std::unique_ptr<deepracer::service::lidar::skeleton::SvLidarSkeletonImpl> m_interface;
    
    /// @brief Data for event, LidEvent
    deepracer::service::lidar::skeleton::events::LidEvent::SampleType m_LidEventData;
};
 
} /// namespace port
} /// namespace aa
} /// namespace lidar
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_LIDAR_AA_PPORTLIDAR_H